# Generated by Django 5.0.1 on 2024-07-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('nombre', models.CharField(max_length=12)),
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('nombre', models.CharField(max_length=12)),
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[(1, 'Japon'), (2, 'España'), (3, 'Corea'), (4, 'Mexico'), (5, 'Estados Unidos'), (6, 'Uruguay'), (7, 'Reino Unido'), (8, 'China'), (9, 'Alemania'), (10, 'Paris'), (11, 'Chile')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nombre', models.CharField(max_length=12)),
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('correo_electronico', models.EmailField(max_length=15)),
                ('genero', models.CharField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], max_length=9)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_pasajeros', models.PositiveIntegerField()),
                ('monto_contrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnTour.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_escolar', models.CharField(choices=[(1, 'Basica'), (2, 'Media')], max_length=6)),
                ('nombre_instituto', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(blank=True, max_length=15)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnTour.ciudad')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnTour.comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnTour.region')),
            ],
        ),
    ]
