# Generated by Django 5.0.6 on 2024-07-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnTour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='nivel_escolar',
            field=models.CharField(choices=[('Basica', 'Basica'), ('Media', 'Media')], max_length=6),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(choices=[('Japon', 'Japon'), ('España', 'España'), ('Corea', 'Corea'), ('Mexico', 'Mexico'), ('Estados Unidos', 'Estados Unidos'), ('Uruguay', 'Uruguay'), ('Reino Unido', 'Reino Unido'), ('China', 'China'), ('Alemania', 'Alemania'), ('Paris', 'Paris'), ('Chile', 'Chile')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=9),
        ),
    ]
